function Hd = bp
%BP Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and DSP System Toolbox 9.9.
% Generated on: 26-Jul-2020 18:14:04

% Chebyshev Type II Bandstop filter designed using FDESIGN.BANDSTOP.

% All frequency values are in Hz.
Fs = 100;  % Sampling Frequency

Fpass1 = 7;           % First Passband Frequency
Fstop1 = 7.94;        % First Stopband Frequency
Fstop2 = 7.96;        % Second Stopband Frequency
Fpass2 = 9;           % Second Passband Frequency
Apass1 = 0.5;         % First Passband Ripple (dB)
Astop  = 60;          % Stopband Attenuation (dB)
Apass2 = 1;           % Second Passband Ripple (dB)
match  = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.bandstop(Fpass1, Fstop1, Fstop2, Fpass2, Apass1, Astop, ...
                      Apass2, Fs);
Hd = design(h, 'cheby2', 'MatchExactly', match);

% [EOF]
